### PR TITLE
Remove hardcoded font size

### PR DESCRIPTION
**Pull request by nevir**
I'd like to be able to inherit the font size where I can. Not sure if this goes counter to Atom theming (still learning it), but the fixed font size was really confusing.

### CODE REVIEW

**Comment by benogle** [comment]
This should probably use `@font-size` or something, eh? @simurai wdyt?

**Comment by simurai** [comment]
If `font-size: 12px;` is removed, it inherits from `body` which uses the `@font-size` variable. So I guess it should be fine.

But most themes use quite a small `@font-size`. So the description in the Style Guide could be a bit bigger. One uses `11px`:

screen shot 2015-02-03 at 9 41 29 am

So maybe those `<p>`s size should be increased a bit. @nevir I can send you a PR, unless you feel like digging into it.

**Comment by nevir** [comment]
Hmm. Well, I'm assuming that `@font-size` is intended to be the default/standard font size for the theme. It feels pretty inconsistent right now, though:

* Most text in the various non-editor panes currently is forced into a larger font size (typically `13px` or `14px`). The various settings views are the easiest example of this.
* Most navigation elements, and some buttons end up using the typically smaller `@font-size`

Maybe we need multiple standard font sizes? `@font-size-pane`, `@font-size-nav` or something?

**Comment by nevir** [comment]
Oh, for reference - the theme I'm working on: https://github.com/nevir/atom-nevish-ui and https://github.com/nevir/atom-nevish-syntax

**Comment by simurai** [comment]
Right, other places would also benefit from having a more flexible font-size. Related: https://github.com/atom/atom/issues/4342 and https://github.com/atom/atom/issues/3792.

I haven't looked into it yet, but I could see a couple options:

1. Like you mentioned above, have a couple more "official" font size variables. The only problem is that it would be a bit late. Not sure if we can "force" the 100s of themes already published to include the new variables. Maybe for those it would just fall back to `@font-size`, but in most cases it would look quite small.
2. Use `rem/em`s everywhere. So all the font-sizes would be just defined as a ratio and not a fixed value. @braver tried that already in the Isotope theme. A problem with using `rem/em`s is that with small sizes, it could be mis-aligned by 1px because the rendering engine tries to round and snap to whole pixels.
3. Calculate the size in Less. Like `font-size: @font-size * 1.5`. It would be similar to `rem`s where  everything is defined as a ratio instead of using fixed `px`. And in this case be based on @font-size. This would allow to scale everything up/down when changing the @font-size variable. And to avoid the "pixel snapping" issue, it could be rounded with `font-size: round(@font-size * .75)`.

Any preferences? I'll try to do some testing and see what would work best.

Ohh.. and another issue is that the Settings and some other places use Bootstrap which uses `px` too. Bootstrap's base font size seems to be [14px](https://github.com/twbs/bootstrap/blob/master/less/variables.less#L51). Maybe it's possible to override it with a theme's `@font-size`? Something like `@font-size-base:  round(@font-size * 1.2);`.

**Comment by braver** [comment]
> Like you mentioned above, have a couple more "official" font size variables. 

You should be able to get away with 4 sizes (S, M, L, XL). Still, you would need a way to change them. Via configurable [theme variables](https://github.com/atom/settings-view/pull/275) perhaps. Changing them is easier if they're based on a single value, so you might want to use a ratio here anyway. Which basically does the same as your other options.

> Use rem/ems everywhere.

This was the way to go for [me](https://github.com/atom/settings-view/pull/275), but I wanted to do the entire layout using the same values and ratios as the typography and at the same time allow on the fly resizing without waiting for configurable theme variables.
But you can also have a fixed pixel based layout while still allowing users to tweak the font-size. Of course at some point it won't fit anymore, but one or two points larger can make all the difference without breaking the layout. 
I did have some issues with left over pixels screwing with alignment, but I've been able to overcome most of them and don't see any real issues at small font-sizes. Even so, being able to choose a 9px font even though its not fully supported seems preferable to not having that choice.

> Calculate the size in Less. Like font-size: @font-size * 1.5. 

This accomplished the same as rems really. The only reason rems are preferable is because they can take the user agent styles into account. This allows someone to deviate from the default 16px body font-size and have a website respect that and adapt. And it allows [isotope](https://github.com/braver/isotope-ui) to adapt to a users stylesheet. But in Atom, as soon as there's a theme variables feature, you really have no use for rems. This option accomplishes the same but allows you to round values to full pixels which is very nice. It even allows you to do `@font-size - 1`, which is much nicer than using ratios for tiny font-sizes.

Bootstrap can be customised, I'm don't know how it works but I bet you change that base font size and then use your third option.

**Comment by simurai** [comment]
@nevir This is now merged. Thanks.

I also increased the font-size of `h2` + `p`s since most themes use a small `@font-size` variable.

**Pull request merged**
